export const PLATFORMS = [
  { id: 'github', name: 'GitHub', color: '181717', icon: 'github' },
  { id: 'linkedin', name: 'LinkedIn', color: '0A66C2', icon: 'linkedin' },
  { id: 'twitter', name: 'Twitter', color: '1DA1F2', icon: 'twitter' },
  { id: 'x', name: 'X', color: '000000', icon: 'x' },
  { id: 'youtube', name: 'YouTube', color: 'FF0000', icon: 'youtube' },
  { id: 'twitch', name: 'Twitch', color: '9146FF', icon: 'twitch' },
  { id: 'discord', name: 'Discord', color: '5865F2', icon: 'discord' },
  { id: 'stackoverflow', name: 'Stack Overflow', color: 'F58025', icon: 'stackoverflow' },
  { id: 'medium', name: 'Medium', color: '12100E', icon: 'medium' },
  { id: 'facebook', name: 'Facebook', color: '1877F2', icon: 'facebook' },
  { id: 'instagram', name: 'Instagram', color: 'E4405F', icon: 'instagram' },
  { id: 'tiktok', name: 'TikTok', color: '000000', icon: 'tiktok' },
  { id: 'devto', name: 'Dev.to', color: '0A0A0A', icon: 'devdotto' },
  { id: 'hashnode', name: 'Hashnode', color: '2962FF', icon: 'hashnode' },
  { id: 'dribbble', name: 'Dribbble', color: 'EA4C89', icon: 'dribbble' },
  { id: 'behance', name: 'Behance', color: '1769FF', icon: 'behance' },
  { id: 'portfolio', name: 'Portfolio', color: '2563EB', icon: 'globe' },
  { id: 'email', name: 'Email', color: 'D14836', icon: 'gmail' },
];
