export interface SkillDefinition {
  name: string;
  icon: string;
}

export const POPULAR_SKILLS: SkillDefinition[] = [
  { name: 'React', icon: 'react' },
  { name: 'TypeScript', icon: 'typescript' },
  { name: 'Node.js', icon: 'nodedotjs' },
  { name: 'Python', icon: 'python' },
  { name: 'JavaScript', icon: 'javascript' },
  { name: 'HTML5', icon: 'html5' },
  { name: 'CSS3', icon: 'css3' },
  { name: 'Docker', icon: 'docker' },
  { name: 'Kubernetes', icon: 'kubernetes' },
  { name: 'AWS', icon: 'amazonaws' },
  { name: 'Tailwind CSS', icon: 'tailwindcss' },
  { name: 'Next.js', icon: 'nextdotjs' },
  { name: 'Vue.js', icon: 'vuedotjs' },
  { name: 'Angular', icon: 'angular' },
  { name: 'Svelte', icon: 'svelte' },
  { name: 'Go', icon: 'go' },
  { name: 'Rust', icon: 'rust' },
  { name: 'C++', icon: 'cplusplus' },
  { name: 'Java', icon: 'openjdk' },
  { name: 'PostgreSQL', icon: 'postgresql' },
  { name: 'MongoDB', icon: 'mongodb' },
  { name: 'Redis', icon: 'redis' },
  { name: 'GraphQL', icon: 'graphql' },
  { name: 'Figma', icon: 'figma' },
  { name: 'Git', icon: 'git' },
  { name: 'Linux', icon: 'linux' },
  { name: 'Firebase', icon: 'firebase' },
  { name: 'Supabase', icon: 'supabase' },
  { name: 'Vercel', icon: 'vercel' },
  { name: 'Prisma', icon: 'prisma' },
  { name: 'Spring Boot', icon: 'springboot' },
  { name: 'Django', icon: 'django' },
  { name: 'Flask', icon: 'flask' },
  { name: 'FastAPI', icon: 'fastapi' },
  { name: 'NestJS', icon: 'nestjs' },
  { name: 'Express', icon: 'express' },
  { name: 'Laravel', icon: 'laravel' },
  { name: 'PHP', icon: 'php' },
  { name: 'Ruby', icon: 'ruby' },
  { name: 'Ruby on Rails', icon: 'rubyonrails' },
  { name: 'Swift', icon: 'swift' },
  { name: 'Kotlin', icon: 'kotlin' },
  { name: 'Flutter', icon: 'flutter' },
  { name: 'Dart', icon: 'dart' },
  { name: 'React Native', icon: 'react' },
  { name: 'Unity', icon: 'unity' },
  { name: 'Unreal Engine', icon: 'unrealengine' },
  { name: 'TensorFlow', icon: 'tensorflow' },
  { name: 'PyTorch', icon: 'pytorch' },
  { name: 'Pandas', icon: 'pandas' },
  { name: 'NumPy', icon: 'numpy' },
  { name: 'MySQL', icon: 'mysql' },
  { name: 'SQLite', icon: 'sqlite' },
  { name: 'Microsoft Azure', icon: 'microsoftazure' },
  { name: 'Google Cloud', icon: 'googlecloud' },
  { name: 'DigitalOcean', icon: 'digitalocean' },
  { name: 'NGINX', icon: 'nginx' },
  { name: 'Apache', icon: 'apache' },
  { name: 'Jenkins', icon: 'jenkins' },
  { name: 'GitHub Actions', icon: 'githubactions' },
  { name: 'GitLab', icon: 'gitlab' },
];
