export interface SkillDefinition {
  name: string;
  icon: string;
  color?: string; // Hex color without the #
}

export const POPULAR_SKILLS: SkillDefinition[] = [
  { name: 'React', icon: 'react', color: '61DAFB' },
  { name: 'TypeScript', icon: 'typescript', color: '3178C6' },
  { name: 'Node.js', icon: 'nodedotjs', color: '339933' },
  { name: 'Python', icon: 'python', color: '3776AB' },
  { name: 'JavaScript', icon: 'javascript', color: 'F7DF1E' },
  { name: 'HTML5', icon: 'html5', color: 'E34F26' },
  { name: 'CSS3', icon: 'css3', color: '1572B6' },
  { name: 'Docker', icon: 'docker', color: '2496ED' },
  { name: 'Kubernetes', icon: 'kubernetes', color: '326CE5' },
  { name: 'AWS', icon: 'amazonaws', color: '232F3E' },
  { name: 'Tailwind CSS', icon: 'tailwindcss', color: '06B6D4' },
  { name: 'Next.js', icon: 'nextdotjs', color: '000000' },
  { name: 'Vue.js', icon: 'vuedotjs', color: '4FC08D' },
  { name: 'Angular', icon: 'angular', color: 'DD0031' },
  { name: 'Svelte', icon: 'svelte', color: 'FF3E00' },
  { name: 'Go', icon: 'go', color: '00ADD8' },
  { name: 'Rust', icon: 'rust', color: '000000' },
  { name: 'C++', icon: 'cplusplus', color: '00599C' },
  { name: 'Java', icon: 'openjdk', color: 'ED8B00' },
  { name: 'PostgreSQL', icon: 'postgresql', color: '4169E1' },
  { name: 'MongoDB', icon: 'mongodb', color: '47A248' },
  { name: 'Redis', icon: 'redis', color: 'DC382D' },
  { name: 'GraphQL', icon: 'graphql', color: 'E10098' },
  { name: 'Figma', icon: 'figma', color: 'F24E1E' },
  { name: 'Git', icon: 'git', color: 'F05032' },
  { name: 'Linux', icon: 'linux', color: 'FCC624' },
  { name: 'Firebase', icon: 'firebase', color: 'FFCA28' },
  { name: 'Supabase', icon: 'supabase', color: '3ECF8E' },
  { name: 'Vercel', icon: 'vercel', color: '000000' },
  { name: 'Prisma', icon: 'prisma', color: '2D3748' },
  { name: 'Spring Boot', icon: 'springboot', color: '6DB33F' },
  { name: 'Django', icon: 'django', color: '092E20' },
  { name: 'Flask', icon: 'flask', color: '000000' },
  { name: 'FastAPI', icon: 'fastapi', color: '009688' },
  { name: 'NestJS', icon: 'nestjs', color: 'E0234E' },
  { name: 'Express', icon: 'express', color: '000000' },
  { name: 'Laravel', icon: 'laravel', color: 'FF2D20' },
  { name: 'PHP', icon: 'php', color: '777BB4' },
  { name: 'Ruby', icon: 'ruby', color: 'CC342D' },
  { name: 'Ruby on Rails', icon: 'rubyonrails', color: 'CC0000' },
  { name: 'Swift', icon: 'swift', color: 'F05138' },
  { name: 'Kotlin', icon: 'kotlin', color: '7F52FF' },
  { name: 'Flutter', icon: 'flutter', color: '02569B' },
  { name: 'Dart', icon: 'dart', color: '0175C2' },
  { name: 'React Native', icon: 'react', color: '61DAFB' },
  { name: 'Unity', icon: 'unity', color: '000000' },
  { name: 'Unreal Engine', icon: 'unrealengine', color: '0E1128' },
  { name: 'TensorFlow', icon: 'tensorflow', color: 'FF6F00' },
  { name: 'PyTorch', icon: 'pytorch', color: 'EE4C2C' },
  { name: 'Pandas', icon: 'pandas', color: '150458' },
  { name: 'NumPy', icon: 'numpy', color: '013243' },
  { name: 'MySQL', icon: 'mysql', color: '4479A1' },
  { name: 'SQLite', icon: 'sqlite', color: '003B57' },
  { name: 'Microsoft Azure', icon: 'microsoftazure', color: '0089D6' },
  { name: 'Google Cloud', icon: 'googlecloud' },
  { name: 'DigitalOcean', icon: 'digitalocean' },
  { name: 'NGINX', icon: 'nginx' },
  { name: 'Apache', icon: 'apache' },
  { name: 'Jenkins', icon: 'jenkins' },
  { name: 'GitHub Actions', icon: 'githubactions' },
  { name: 'GitLab', icon: 'gitlab' },
];
